### ISSUE TITLE
Tracking DLL

### ISSUE THREAD

**Issue by Tare05** [hasherezade/tiny_tracer#1]
Question
=======

**Hello!**

Is there a way to get a track dump from just a DLL file specificly? 

Also thanks for all the great tools, they really help me out!

**Comment by hasherezade** [comment]
Hello!
Yes, it is possible to trace a selected DLL rather than the main EXE.
First, make sure that you copied the latest [run_me.bat](https://github.com/hasherezade/tiny_tracer/blob/master/install32_64/run_me.bat). You will see the line:
```
rem TRACED_MODULE - by default it is the main module, but it can be also a DLL within the traced process
set TRACED_MODULE=%TARGET_APP%
```
You need to change the traced module to your DLL, i.e.:
```
rem TRACED_MODULE - by default it is the main module, but it can be also a DLL within the traced process
set TRACED_MODULE=user32.dll
```
Now it will trace the mentioned DLL and generate tags for it, i.e. `user32.dll.tag`

**Comment by Tare05** [comment]
Thank you for your fast answer!

**Comment by hasherezade** [comment]
@Tare05 - you are welcome! now this topic is also covered in the [Tiny Tracer's Wiki](https://github.com/hasherezade/tiny_tracer/wiki)
