### ISSUE TITLE
Programs packaged with vmp do not result.

### ISSUE THREAD

**Issue by maskelihileci** [hasherezade/tiny_tracer#17]
Good day, I was using tiny racer v 1.4. I was getting results without any issues

I updated to version 2.0 today Can analyze unpackaged programs nicely but software packaged with vmp keeps working forever.
I waited for 20 minutes, the pin is working in the background. The program runs in the background, but it never completes. So it never reaches the oep point.

779a61;section: [.vmp1]
82404d;kernel32.LocalAlloc
7972b0;kernel32.GetModuleHandleA
7972b0;kernel32.GetModuleHandleA
8b56e0;kernel32.GetModuleFileNameW
7df6d1;kernel32.LocalAlloc

Windows 10 1607
pin-3.20
i7 6700K
Visual Studio 2019 (v142)

**Comment by maskelihileci** [comment]
Current status ; I extended the waiting time a little longer and wanted it to work until the result came. The result has arrived
But its performance is very slow . The source of this slowness is probably one of the newly added features. 
So my advice to you is to set a config that will disable this feature and improve performance.

**Comment by hasherezade** [comment]
hi! thank you for reporting. 
I suspect what may be slowing it down, but I need to make some more tests. Could you please share the sample on which you was testing? I checked on some VMProtect-protected sample but didn't notice such a drastic performance loss (possibly my sample was packed with different settings), so I would prefer to use the same what you was using, in order to be precise. You can drop it here (packed with a password) or send to my e-mail: hasherezade-at-pm.me.
Also, please share what are the settings of TinyTracer  that you use (the INI file).

**Comment by hasherezade** [comment]
I reviewed  the changes in the TinyTracer, and the feature that I suspected to be causing the slow down turns out to be added before 1.4. So, could you please just make a test for me, to make sure that the slow down is not caused by the changes in the Pin itself? 

I added a project `TinyTracer.old.vcxproj` that allows to build the latest TinyTracer with Pin < 3.19. Could build the version 2.0 of TinyTracer with the old Pin, which you used with 1.4, and check if the same problem occurs?

**Comment by hasherezade** [comment]
@maskelihileci please let me know the results ^

**Comment by maskelihileci** [comment]
Sorry for the late reply I was sick
I will now review

**Comment by maskelihileci** [comment]
Pin-3.17 used on 2.0 unfortunately still slow
CPU usage is the same 12%
The only difference I've found now is the pincrt.dll module. 

Tiny 1.4 = pincrt.dll not loading
Tiny 2.0 = pincrt.dll loading

Maybe it has nothing to do with it, but this is what I see right now.

**Comment by maskelihileci** [comment]
If there is a discord server we can contact, we can solve the problem more easily.

**Comment by hasherezade** [comment]
I am not on Discord, but I am on Wire (https://wire.com), my login is the same as here.
If you can just send me the sample that is causing you the problems I will handle it. Without reproducing it it is very hard.

**Comment by hasherezade** [comment]
@maskelihileci  - ok, now you can find me on Discord too. I am `hasherezade#9405`

**Comment by maskelihileci** [comment]
I added you as a friend and sent a message

**Comment by hasherezade** [comment]
Thank you, I reproduced this problem, and working on the fix.
Those are my benchmarks:
*version 1.9*
![bench_1 9](https://user-images.githubusercontent.com/3115348/150123064-bdcb4135-d593-4851-98e4-17e4b5f5b080.png)

*version 1.9.5*
![benchmark_1 9 5](https://user-images.githubusercontent.com/3115348/150123172-27f4febc-60f2-4d0a-8a8e-672f91918258.png)

*version 2.0*
![benchmark_2 0](https://user-images.githubusercontent.com/3115348/150123197-693fe77c-fbe1-41ae-b026-4bb2f518677f.png)

The commit that caused the slowdown to the unacceptable values was this: https://github.com/hasherezade/tiny_tracer/commit/8493e3c82a210a49c46e56090bfae49c52278e35

![benchmark_commit_8493](https://user-images.githubusercontent.com/3115348/150123399-9450089d-26f9-4c78-958e-629ac49e4851.png)

**Comment by hasherezade** [comment]
I merged it, and run the benchmark, this is my result:

![benchmark_2 1](https://user-images.githubusercontent.com/3115348/150136311-de353f84-cc7f-41c4-a7c0-4d5c49c6b820.png)

I think this is acceptable, what do you think?

**Comment by maskelihileci** [comment]
Problem solved, thanks for your attention.
