### ISSUE TITLE
Run with PIN as Administrator

### ISSUE THREAD

**Issue by Xelentra1** [hasherezade/tiny_tracer#3]
Hey! 

Sorry if it is stupid question but how to run an executable file with PIN as Administrator?

**Comment by hasherezade** [comment]
Actually, it is not a stupid question. And a good idea to add a menu to run with PIN as an Administrator.

![pin_menus](https://user-images.githubusercontent.com/3115348/85497774-cde62280-b5de-11ea-8746-2c21ce9ad98f.png)

I added a new menu that allows for this. For now I am improving the feature, so it is not in the official release yet. But you can get it if you clone the repo, and switch to the branch `admin_menu`. You need to delete the old menus first by `delete_menu.reg`, and then add them again.

Also make sure that your Administrator account is enabled in the group policy, otherwise it will not run. 
In Group Policy Editor:
`Computer Configuration` -> `Windows Settings` -> `Security Settings` -> `Local Policies` -> `Security Options` ->` Accounts: Administrator account status`:`Enabled`

**Comment by Xelentra1** [comment]
Nice feature, thank you!

**Comment by zin1x** [comment]
> PIN is trying to run the app:
> "C:\Users\user\Desktop\putty.exe"
> 64bit selected
> Target module: "C:\Users\user\Desktop\putty.exe"
> Tag file: "C:\Users\user\Desktop\putty.exe.tag"
> Attempting to start C:\pin\\pin.exe -t C:\pin\source\tools\tiny_tracer\install32_64\\TinyTracer64.dll -m C:\Users\user\Desktop\putty.exe -o C:\Users\user\Desktop\putty.exe.tag -f 1 -s 1 -- C:\Users\user\Desktop\putty.exe  as user "WIN-XXXX\Administrator" ...
> Enter the password for Administrator:
> Attempting to start C:\pin\\pin.exe -t C:\pin\source\tools\tiny_tracer\install32_64\\TinyTracer64.dll -m C:\Users\user\Desktop\putty.exe -o C:\Users\user\Desktop\putty.exe.tag -f 1 -s 1 -- C:\Users\user\Desktop\putty.exe  as user "WIN-XXXX\Administrator" ...
> RUNAS ERROR: Unable to run - C:\pin\\pin.exe -t C:\pin\source\tools\tiny_tracer\install32_64\\TinyTracer64.dll -m C:\Users\user\Desktop\putty.exe -o C:\Users\user\Desktop\putty.exe.tag -f 1 -s 1 -- C:\Users\user\Desktop\putty.exe
> -2147467259: Unspecified error
>  Press any key to continue . . .


Getting this error when trying to run as administrator. Normal run works fine

**Comment by hasherezade** [comment]
@zin1x - it is something related with your system settings (check [Group Policy](https://github.com/hasherezade/tiny_tracer/wiki/Tracing-as-Administrator) ). But is hard for me to debug it remotely and pinpoint where exactly the problem lies, because I don't have access to your system, and the error is "unspecified" (`-2147467259: Unspecified error`).

This feature makes a use of [`runas`](https://github.com/hasherezade/tiny_tracer/blob/master/install32_64/run_me.bat#L39) - so, if for some reason `runas` is restricted, or the Administrator account disabled from the use, it will not run.

**Comment by hasherezade** [comment]
I changed the way to elevate the process: https://github.com/hasherezade/tiny_tracer/commit/4d5b9f013b1ec9fdbb64f768afadfb3706a778b5 - please update and let me know if it helps

**Comment by zin1x** [comment]
> I changed the way to elevate the process: [4d5b9f0](https://github.com/hasherezade/tiny_tracer/commit/4d5b9f013b1ec9fdbb64f768afadfb3706a778b5) - please update and let me know if it helps

Looks like it's working now. Thanks!

**Comment by hasherezade** [comment]
@ zin1x - cool, so I will make an updated release.
